# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'PCS'
tagline:          'JS Immersion'
description:      'JavaScript Immersion'
url:              http://portlandcodeschool.github.io/jsi
baseurl:          /jsi
timezone:         UTC

author:
  name:           'Andrew Lorente'
  url:            https://twitter.com/AndrewLorente

# Custom vars
version:          2.1.0b
