# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'PCS'
tagline:          'JS Immersion'
description:      'JavaScript Immersion'
url:              http://portlandcodeschool.github.io/jsi
baseurl:          /jsi
timezone:         GMT

author:
  name:           'Whitney Young'
  url:            https://twitter.com/wbyoung

# Custom vars
version:          2.0.2
